#!/usr/bin/env bash

cd module

# Add a `copyDeviceId` call to autogenerated `newTransect()` function
# definition.
string="
  setUuid(tabgroup, null);
  newTabGroup(tabgroup);

  String autoNumDest = \"\";
  autoNumDest = \"Transect\/Transect\/Transect_ID\";
  incAutoNum(autoNumDest);"
replacement="$string
  copyDeviceId();"
perl -0777 -i.original -pe "s/\\Q$string/$replacement/igs" ui_logic.bsh

# Delete autogenerated onClickLoginLogin definition.
string="
onClickLoginLogin () {
  \/\/ TODO: Add some things which should happen when this element is clicked
  newTab(\"Control\", true);
}"
replacement=""
perl -0777 -i.original -pe "s/\\Q$string/$replacement/igs" ui_logic.bsh

# Delete autogenerated loadSiteFrom definition.
string="
loadSiteFrom(String uuid) {
  String tabgroup = \"Site\";
  setUuid(tabgroup, uuid);
  if (isNull(uuid)) return;

  showTabGroup(tabgroup, uuid);
}"
replacement=""
perl -0777 -i.original -pe "s/\\Q$string/$replacement/igs" ui_logic.bsh

rm ui_logic.bsh.original
